fix: Update options conditions (#5)

diff --git a/gfpush b/gfpush
--- a/gfpush
+++ b/gfpush
@@ -1,23 +1,16 @@
 #!/bin/bash
 
-parse_git_branch() {
-    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
+usage() {
+   echo "Try 'gfpush -h' for more information"
 }
 
-all=""
-branch=$(parse_git_branch)
-scope=""
-message=""
-commit_type=-1
-exclamation_mark=""
+parse_git_branch() {
+   git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
+}
 
-declare TYPE=( [1]="build" [2]="chore" [3]="ci" [4]="docs" 
-               [5]="feat" [6]="fix" [7]="perf" [8]="refactor"
-               [9]="revert" [10]="style" [11]="test" )
+VERSION="1.0.0"
 
-version="0.1.2"
-
-help="
+HELP="
 NAME:
    gfpush - Git Fast Push
 
@@ -57,32 +50,126 @@ EXAMPLE:
     gfpush -e -t 5 -s api -m 'Add metrics'   --> feat(api)!: Add metrics
 "
 
-while getopts hvaem:s:t: opt; do
-  case "$opt" in
-      a) all="-a";;
-      e) exclamation_mark="!";;
-      h) echo "$help"; exit 0;;
-      m) message="$OPTARG";;
-      s) scope="($OPTARG)";;
-      t) commit_type="$OPTARG";;
-      v) echo "gfpush version $version"; exit 0;;
-  esac
+# while getopts "hvaem:s:t:" opt; do
+#   case "$opt" in
+#       a) 
+#          all="-a"
+#       ;;
+#       e)
+#          exclamation_mark="!"
+#       ;;
+#       h)
+#          echo "$help"
+#          exit 0
+#       ;;
+#       m)
+#          message="$OPTARG"
+#       ;;
+#       s) 
+#          scope="$OPTARG"
+#       ;;
+#       t) 
+#          COMMIT_TYPE="$OPTARG"
+#          echo "$COMMIT_TYPE"
+#          if [[ "$COMMIT_TYPE" -le "0" ]]  || [[ "$COMMIT_TYPE" -ge "12" ]] || [[ ! -n "$COMMIT_TYPE" ]]; then
+#             echo "1: build  3: ci    5: feat  7: perf      9: revert  11: test 
+#          2: chore  4: docs  6: fix   8: refactor  10: style"
+#             exit 1
+#          fi
+#       ;;
+#       v) echo "gfpush version $version"
+#          exit 0
+#       ;;
+   	# :)
+		# 	echo "Option -$OPTARG requires an argument (getopts)" >&2
+		# 	exit 1
+		# ;;
+      # \?)
+		# 	echo "Invalid option: -$OPTARG" >&2
+		# 	exit 1
+      # ;;
+#   esac
+# done
+
+# if [[ "$COMMIT_TYPE" -le 0 ]]  || [[ "$COMMIT_TYPE" -ge 12 ]] || [[ ! -n "$COMMIT_TYPE" ]]; then
+#   echo "1: build  3: ci    5: feat  7: perf      9: revert  11: test 
+# 2: chore  4: docs  6: fix   8: refactor  10: style";
+#   exit 1;
+# fi
+
+# if [[ ! -n "$message" ]]; then
+#   exit 1;
+# fi
+
+BRANCH=$(parse_git_branch)
+
+declare TYPE=( [1]="build" [2]="chore" [3]="ci" [4]="docs" 
+               [5]="feat" [6]="fix" [7]="perf" [8]="refactor"
+               [9]="revert" [10]="style" [11]="test" )
+
+
+while getopts "ahm:st:v" options; do
+   case "$options" in
+   a)
+      # git commit <-a> flag
+      FLAG_ALL="-a"
+   ;;
+   e)
+      # exclamation mark
+      FLAG_E_MARK="!" 
+   ;;
+   h)
+      echo "$HELP"
+      exit 0
+   ;;
+   m)
+      MESSAGE="$OPTARG"
+      if [[ ! -n "$MESSAGE" ]]; then
+         echo "Make sure commit message is not empty"
+      fi
+   ;;
+   s) 
+      SCOPE="$OPTARG"
+   ;;
+   t)
+      COMMIT_TYPE="$OPTARG"
+      if [[ "$COMMIT_TYPE" -le "0" ]]  || [[ "$COMMIT_TYPE" -ge "12" ]] || [[ ! -n "$COMMIT_TYPE" ]]; then
+         echo -e "1: build   2: chore     3: ci\n4: docs    5: feat      6: fix\n7: perf    8: refactor  9: revert\n10: style  11: test"
+         exit 1
+      fi
+   ;;
+   v)
+      echo "gfpush version $VERSION"
+      exit 0
+   ;;
+   *)
+      usage
+      exit 1
+   ;;
+   esac
 done
 
-
-if [[ "$commit_type" -le 0 ]]  || [[ "$commit_type" -ge 12 ]] || [[ ! -n "$commit_type" ]]; then
-  echo "1: build  3: ci    5: feat  7: perf      9: revert  11: test 
-2: chore  4: docs  6: fix   8: refactor  10: style";
-  exit 1;
-fi
-
-if [[ ! -n "$message" ]]; then
-  exit 1;
+if [ -z "$MESSAGE" ] || [ -z "$COMMIT_TYPE" ]; then
+   usage
+   exit 1
 fi
 
 echo "Commiting file(s) status:";
-git status -s
+git status -s;
 echo;
-eval "git commit -q $all -m '${TYPE[$commit_type]}$scope$exclamation_mark: $message' && git push -q origin $branch";
+
+eval "git commit $FLAG_ALL -m '${TYPE[$COMMIT_TYPE]}$SCOPE$FLAG_E_MARK: $MESSAGE'";
+if [[ "$?" -gt 0 ]]; then
+   exit 1
+fi
+
+echo;
+
+eval "git push -q origin $BRANCH";
+if [[ "$?" -gt 0 ]]; then
+   exit 1
+fi
+
 echo "Everything up-to-date 🚀";
+
 exit 0
